namespace SmartLab.XBee.Status
{
    public enum ReceiveStatus
    {
        SUCCESS = 0x00,
        PACKET_ACKNOWLEDGED = 0x01,
        PACKET_WAS_A_BROADCAST = 0x02,
        PACKET_RECEIVED_ON_BOARDCAST_PAN = 0x04,
        BROADCAST_PACKET_RECEIVED_ON_BOARDCAST_PAN = 0x06,
        PACKET_ENCRYPTED_WITH_APS_ENCRYPTION = 0x20,
        PACKET_WAS_SENT_FROM_AN_END_DEVICE = 0x40,
        PACKET_ENCRYPTED_WITH_APS_ENCRYPTION_AND_ACKNOWLEDGED = 0x21,
        PACKET_WAS_A_BROADCAST_PACKET_ENCRYPTED_WITH_APS_ENCRYPTION = 0x22,
        PACKET_ACKNOWLEDGED_AND_WAS_SENT_FROM_AN_END_DEVICE = 0x41,
        PACKET_WAS_A_BROADCAST_PACKET_SENT_FROM_AN_END_DEVICE = 0x42,
        PACKET_WAS_SENT_FROM_AN_END_DEVICE_AND_ENCRYPTED_WITH_APS_ENCRYPTION = 0x60,
        ACKNOWLEDGED_PACKET_SENT_FROM_AN_END_DEVICE_AND_ENCRYPTED_WITH_APS_ENCRYPTION = 0x61,
        BROADCAST_PACKET_WAS_SENT_FROM_AN_END_DEVICE_AND_ENCRYPTED_WITH_APS_ENCRYPTION = 0x62,
    }
}
